language: node_js
node_js:
  - "node"
branches:
  only:
  - master
before_script:
  - echo "module.exports = require('./travis.js')" > config/env/env.js
script:
  - npm run minify & npm run build

# Send coverage data to Coveralls
after_script: 
  - npm run cover && cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js