language: node_js
node_js:
  - "node"
branches:
  only:
  - master
before_install:
  - echo "module.exports = require('./travis.js')" > config/env/env.js
script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"